<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DNID0694L01" ignored="0" name="QuotaAppTest" tests="37" failures="34" timestamp="18 May 2020 11:38:21 GMT" time="129.773" errors="0">
  <testcase name="testForgotPassword" time="2.74" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword"/>
  <testcase name="testForgotPassword" time="2.863" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.488" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword"/>
  <testcase name="testForgotPassword" time="2.972" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.864" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.895" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.632" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.811" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.972" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.073" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword"/>
  <testcase name="testForgotPassword" time="4.335" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.854" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.814" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.044" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.865" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.661" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.685" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.199" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.738" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.659" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.868" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.914" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.014" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.583" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.157" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.914" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.43" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.254" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.795" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.419" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.512" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.515" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.062" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.485" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="3.001" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.608" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
  <testcase name="testForgotPassword" time="2.825" classname="com.g2academy.testcases.loginmenu.TC_ForgotPassword">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_ForgotPassword.testForgotPassword(TC_ForgotPassword.java:95)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testForgotPassword -->
</testsuite> <!-- QuotaAppTest -->
