<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DNID0694L01" name="com.g2academy.testcases.loginmenu.TC_Register" tests="99" failures="15" timestamp="18 May 2020 12:56:04 GMT" time="679.501" errors="0">
  <testcase name="testRegister" time="7.068" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.758" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.553" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.520" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.270" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.576" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.917" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.192" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.554" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.168" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.890" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.256" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.191" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.621" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.982" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.373" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.317" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.961" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.760" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.430" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.145" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.928" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.551" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.714" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.577" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.167" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.736" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.168" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.062" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.763" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.747" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.438" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.233" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.152" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.550" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.169" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.026" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.161" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.936" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.350" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.244" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.754" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.370" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.928" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.666" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.428" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.830" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.758" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.781" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.457" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.353" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.084" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.143" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.592" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.340" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.349" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.481" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.593" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.579" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.964" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.985" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.556" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.598" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.611" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.964" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.551" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.395" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.481" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.739" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.172" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.166" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.509" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.762" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.665" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.742" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.601" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.341" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.424" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.964" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.190" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.275" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.489" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.313" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.740" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.572" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.753" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.783" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="7.128" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.379" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.376" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.961" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.580" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.697" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.733" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="8.398" classname="com.g2academy.testcases.loginmenu.TC_Register">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.g2academy.base.Assertion.statusCode(Assertion.java:8)
at com.g2academy.testcases.loginmenu.TC_Register.testRegister(TC_Register.java:90)
at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testRegister -->
  <testcase name="testRegister" time="6.908" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="5.938" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="7.075" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
  <testcase name="testRegister" time="6.363" classname="com.g2academy.testcases.loginmenu.TC_Register"/>
</testsuite> <!-- com.g2academy.testcases.loginmenu.TC_Register -->
